import Head from 'next/head'
import Image from 'next/image'
import { Router } from 'next/router'
import { Bio } from '../components/Bio'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import { Layout } from '../components/layout/Layout'
import { Stack } from '../components/Stack'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Manjesh Hembrom | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cat.ico" />
      </Head>
        <main >
          <Hero />
          <Stack />
          <Bio />
        </main>
    </div>
  )
}
