import Head from 'next/head'
import Image from 'next/image'
import { Bio } from '../components/Bio'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import { PageIndicator } from '../components/PageIndicator'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Manjesh Hembrom | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cat.ico" />
      </Head>
      
      <main >
      <Hero />
      <Bio />

      </main>

      <footer className='w-1/2 text-center mx-auto py-6'>
      <p className='text-slate-400 text-[15px]'>© {new Date().getFullYear()} Manjesh Hembrom. All Rights Reserved.</p>
      </footer>
    </div>
  )
}
