import Head from 'next/head'
import Image from 'next/image'
import { Router } from 'next/router'
import { Bio } from '../components/Bio'
import { Header } from '../components/Header'
import { Hero } from '../components/Hero'
import { Layout } from '../components/layout/Layout'
import { Stack } from '../components/Stack'
import { Summery } from '../components/Summery'

export default function Home() {

  const description = "I'm full-stack developer ans I like making things on React/Nextjs ans Flutter";
  const pageTitle = "Manjesh Portfolio";
  const twitterHandle = "@HembromManjesh";
  const currentURL = "https://mkhembrom.com";
  const previewImage = "/previwImage.png";
  const siteName = "mkhembrom.com";

  return (
    <div className=''>
      <Head>
        <title>Manjesh Hembrom | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <meta name="description" content={description} />
        <meta property="og:title" content={pageTitle} key="ogtitle" />
        <meta property="og:description" content={description} key="ogdesc" />
        {/* Twitter */}
        <meta name="twitter:card" content="summary" key="twcard" />
        <meta name="twitter:creator" content={twitterHandle} key="twhandle" />

        {/* Open Graph */}
        <meta property="og:url" content={currentURL} key="ogurl" />
        <meta property="og:image" content={previewImage} key="ogimage" />
        <meta property="og:site_name" content={siteName} key="ogsitename" />
        <meta property="og:title" content={pageTitle} key="ogtitle" />
        <meta property="og:description" content={description} key="ogdesc" />
        <link rel="icon" href="/cat.ico" />
      </Head>
      <main >
        <Hero />
        <Stack />
        <Summery />
        <Bio />
      </main>
    </div>
  )
}
